POST localhost:8080/login
Content-Type: application/json

{

  "email": "dijialei@gmail.com",
  "password": "123456"
}

###
GET localhost:8080/signout
Content-Type: application/json
JWT-TOKEN: eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFMyNTYifQ.eyJzdWIiOiIxIiwibmlja05hbWUiOiJsZWlnZSIsInJvbGVzIjpbImFkbWluIl0sImVtYWlsIjoiZGlqaWFsZWlAZ21haWwuY29tIiwiZXhwIjoxNzIyMDMxMTQxfQ.9ZzjxPwdl7uF8kmzetCp0ebSDt0SF98nz99K4fTjMjM
