POST localhost:8080/users
Content-Type: application/json

{
  "firstName": "li",
  "lastName": "su",
  "nickName": "laopo",
  "email": "suli@gmail.com",
  "password": "123456",
  "roles": ["admin"]
}

###
POST localhost:8080/users
Content-Type: application/json

{
  "firstName": "jialei",
  "lastName": "di",
  "nickName": "leige",
  "email": "dijialei@gmail.com",
  "password": "123456",
  "roles": ["admin"]
}